### ISSUE TITLE
Application failed to start

### ISSUE THREAD

**Issue by charlesdnguyen03** [oganm/swarm#1]
Hello, don't know if this is exactly the best way to contact you for this, but I don't think this works anymore. Whenever I go to https://oganm.com/shiny/swarm/ it just shows up with:
"
An error has occurred
The application failed to start.

The application exited during initialization.
"
This was super useful for me using animate objects, so I was hoping if you could fix it (or put up something that says that the page is dead if you don't want to maintain it). Thanks.

**Comment by oganm** [comment]
sorry about that. the server it's running on isn't having it's best days. just rebooted and should be working fine again
